import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Toollane",
  description:
    "Read the Toollane Terms of Service for using Toollane's free online tools, calculators, file tools, generators and browser-based utilities.",
  alternates: {
    canonical: "https://toollane.net/terms",
  },
  openGraph: {
    title: "Terms of Service | Toollane",
    description:
      "Read the Toollane Terms of Service for using Toollane's free online tools, calculators, file tools, generators and browser-based utilities.",
    url: "https://toollane.net/terms",
    siteName: "Toollane",
    type: "website",
  },
};

const sections = [
  {
    title: "1. Acceptance of these terms",
    content: [
      "By accessing or using Toollane, you agree to these Terms of Service. If you do not agree with these terms, please do not use the website.",
      "These terms apply to all Toollane pages, tools, calculators, generators, file tools, informational pages and related website features.",
    ],
  },
  {
    title: "2. About Toollane",
    content: [
      "Toollane provides free online tools for utility, productivity, file processing, calculations, SEO, text formatting, business tasks, developer tasks, generators and everyday digital workflows.",
      "Toollane is operated by Nicklas Wolf from Germany and is continuously developed and improved.",
    ],
  },
  {
    title: "3. Informational and utility purposes only",
    content: [
      "Toollane tools are provided for informational, educational, productivity and general utility purposes.",
      "Results generated by Toollane tools should be reviewed carefully before being used for important decisions, professional work, legal matters, financial planning, tax decisions, medical decisions, business commitments or other high-impact situations.",
      "Toollane does not provide legal, financial, tax, medical, investment, real estate, mortgage, accounting or professional advice.",
    ],
  },
  {
    title: "4. User responsibility",
    content: [
      "You are responsible for the information, files, text, values or settings you enter into Toollane tools.",
      "You are responsible for checking the accuracy, suitability and completeness of any output before using it.",
      "You should not enter information into Toollane that you are not allowed to process, upload, convert, edit or use.",
    ],
  },
  {
    title: "5. File-based tools",
    content: [
      "Many Toollane file-based tools are designed to work directly in the browser where possible. This can make common file tasks faster and more privacy-friendly.",
      "Tool behavior may vary depending on the browser, device, file size, file type, file structure and selected settings.",
      "You should keep an original copy of important files before editing, converting, compressing, resizing or otherwise processing them with any online tool.",
    ],
  },
  {
    title: "6. Calculators and estimates",
    content: [
      "Toollane calculators provide estimates based on the values entered by the user.",
      "Calculator results may be affected by assumptions, rounding, missing information, regional differences, changing rates, taxes, fees, regulations or market conditions.",
      "For financial, mortgage, business, tax, legal or investment decisions, you should verify results with a qualified professional or official source.",
    ],
  },
  {
    title: "7. Generators and creative tools",
    content: [
      "Toollane generators may create names, ideas, text, codes, prompts, business concepts or other creative outputs.",
      "Generated outputs are suggestions and starting points. You are responsible for reviewing, editing and verifying any generated result before using it publicly or commercially.",
      "For business names, product names, usernames, slogans or brand-related outputs, you should check availability, originality, trademark conflicts and legal suitability before use.",
    ],
  },
  {
    title: "8. Availability and errors",
    content: [
      "Toollane aims to provide fast and reliable tools, but the website may not always be available, uninterrupted, accurate or error-free.",
      "Toollane may update, change, remove, limit or discontinue tools or pages at any time without prior notice.",
      "Toollane is not responsible for losses or damages caused by unavailable tools, incorrect results, browser issues, file errors, user input errors or technical problems.",
    ],
  },
  {
    title: "9. Prohibited use",
    content: [
      "You agree not to use Toollane for illegal, harmful, abusive, misleading, infringing or unauthorized purposes.",
      "You must not attempt to disrupt the website, overload servers, bypass security features, scrape content at scale, reverse engineer systems or interfere with normal website operation.",
      "You must not use Toollane to create, process or distribute content that violates applicable law, third-party rights or platform policies.",
      "If ads are displayed on Toollane, you must not generate artificial impressions, artificial clicks or other invalid advertising activity.",
    ],
  },
  {
    title: "10. Intellectual property",
    content: [
      "The Toollane website, design, branding, page content, tool interfaces, structure and original materials are owned by Toollane or its respective rights holders.",
      "You may use Toollane tools for personal or business productivity, but you may not copy, reproduce, resell or redistribute substantial parts of the website without permission.",
    ],
  },
  {
    title: "11. Third-party services and links",
    content: [
      "Toollane may use third-party services for hosting, analytics, advertising, performance, security or other website functionality.",
      "Toollane may also link to external websites or resources. Toollane is not responsible for the content, accuracy, availability, privacy practices or terms of external websites.",
    ],
  },
  {
    title: "12. Advertising and affiliate links",
    content: [
      "Toollane may earn revenue through advertising, affiliate links or other monetization methods while keeping the tools free to use.",
      "Advertising or affiliate relationships do not change the user's responsibility to review results, compare options and make independent decisions.",
    ],
  },
  {
    title: "13. Privacy",
    content: [
      "Use of Toollane is also subject to the Privacy Policy. The Privacy Policy explains how Toollane may handle browser-based tools, contact requests, cookies, analytics and advertising services.",
      "You should review the Privacy Policy before using Toollane, especially if you use file-based tools or interact with advertising or analytics technologies.",
    ],
  },
  {
    title: "14. Changes to these terms",
    content: [
      "Toollane may update these Terms of Service from time to time. Updated terms will be published on this page.",
      "Continued use of Toollane after changes are published means you accept the updated terms.",
    ],
  },
  {
    title: "15. Contact",
    content: [
      "If you have questions about these Terms of Service, contact Toollane by email using the Contact page.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#fff8df] text-[#171717]">
      <section className="relative overflow-hidden border-b border-black/10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_#ffe680,_transparent_35%),radial-gradient(circle_at_top_right,_#ffd6e7,_transparent_30%)]" />

        <div className="relative mx-auto max-w-5xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20">
          <div className="inline-flex rounded-full border border-black/10 bg-white/70 px-4 py-2 text-sm font-bold shadow-sm backdrop-blur">
            Terms of Service
          </div>

          <h1 className="mt-6 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">
            Terms for using Toollane
          </h1>

          <p className="mt-6 max-w-3xl text-lg leading-8 text-black/65">
            These Terms of Service explain the rules for using Toollane&apos;s
            free online tools, calculators, file tools, generators and
            informational pages.
          </p>

          <p className="mt-5 text-sm font-bold text-black/50">
            Last updated: June 2026
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
        <div className="rounded-[2.5rem] border border-black/10 bg-white/80 p-8 shadow-sm backdrop-blur sm:p-12">
          <div className="space-y-10">
            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="text-2xl font-black tracking-tight text-black">
                  {section.title}
                </h2>

                <div className="mt-5 space-y-4 text-black/70 leading-8">
                  {section.content.map((paragraph) => (
                    <p key={paragraph}>{paragraph}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      </section>

      <section className="border-y border-black/10 bg-white/40">
        <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
          <div className="grid gap-6 lg:grid-cols-2">
            <div className="rounded-[2rem] border border-black/10 bg-white/80 p-8 shadow-sm">
              <h2 className="text-2xl font-black tracking-tight">
                Related legal pages
              </h2>

              <p className="mt-5 leading-8 text-black/65">
                Review the Privacy Policy, Imprint and Contact page for more
                information about Toollane, privacy handling and how to get in
                touch.
              </p>

              <div className="mt-6 flex flex-wrap gap-4">
                <Link
                  href="/privacy-policy"
                  className="text-sm font-bold underline underline-offset-4"
                >
                  Privacy Policy →
                </Link>

                <Link
                  href="/imprint"
                  className="text-sm font-bold underline underline-offset-4"
                >
                  Imprint →
                </Link>

                <Link
                  href="/contact"
                  className="text-sm font-bold underline underline-offset-4"
                >
                  Contact →
                </Link>
              </div>
            </div>

            <div className="rounded-[2rem] border border-black/10 bg-white/80 p-8 shadow-sm">
              <h2 className="text-2xl font-black tracking-tight">
                About Toollane
              </h2>

              <p className="mt-5 leading-8 text-black/65">
                Toollane is a free online tools platform for practical browser
                tasks, including calculators, PDF tools, image tools, SEO tools,
                text tools, generators, developer utilities and business tools.
              </p>

              <div className="mt-6">
                <Link
                  href="/about"
                  className="text-sm font-bold underline underline-offset-4"
                >
                  Learn more about Toollane →
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}